wandb_version: 1

learning_rate_start:
  desc: null
  value: 0.0001
layers:
  desc: null
  value: 2
hidden_nf:
  desc: null
  value: 16
scheduler:
  desc: null
  value: ReduceLROnPlateau
optimizer:
  desc: null
  value: Adam
patience:
  desc: null
  value: 5
factor:
  desc: null
  value: 0.1
dataset:
  desc: null
  value: datasets/files/ala_converged_1000
epochs:
  desc: null
  value: 50
batch-size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723648407
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.12.2
      5: 0.17.4
      8:
      - 4
      - 5
      13: darwin-arm64
