wandb_version: 1

name:
  desc: null
  value: alaninedipeptide
learning_rate_start:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: AdamW
batch_size:
  desc: null
  value: 32
loss_fn:
  desc: null
  value: L1Loss
model_checkpoint:
  desc: null
  value: gnn/models/swag5_20241113_193532/model_4.pt
model:
  desc: null
  value: SWAG
epochs_per_iter:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1732178086
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.12.4
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
