wandb_version: 1

name:
  desc: null
  value: alaninedipeptide
learning_rate_start:
  desc: null
  value: 0.001
layers:
  desc: null
  value: 4
hidden_nf:
  desc: null
  value: 32
scheduler:
  desc: null
  value: ReduceLROnPlateau
optimizer:
  desc: null
  value: AdamW
patience:
  desc: null
  value: 800
factor:
  desc: null
  value: 0.1
dataset:
  desc: null
  value: 1000
epochs:
  desc: null
  value: 10000
batch_size:
  desc: null
  value: 32
in_node_nf:
  desc: null
  value: 12
in_edge_nf:
  desc: null
  value: 0
loss_fn:
  desc: null
  value: L1Loss
model_checkpoint:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725538467
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.17.4
      8:
      - 4
      - 5
      13: darwin-arm64
